//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElSaberDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acceso
    {
        public int IdAcceso { get; set; }
        public string correo { get; set; }
        public string contrasenia { get; set; }
        public string tipoDeUsuario { get; set; }
        public int FK_IdUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
