//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElSaberDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devolucion
    {
        public int IdDevolucion { get; set; }
        public System.DateTime fechaDevolucion { get; set; }
        public string nota { get; set; }
        public string estadoLibro { get; set; }
        public int FK_IdPrestamo { get; set; }
    
        public virtual Prestamo Prestamo { get; set; }
    }
}
