//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElSaberDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libro()
        {
            this.Prestamo = new HashSet<Prestamo>();
        }
    
        public int IdLibro { get; set; }
        public string titulo { get; set; }
        public string isbn { get; set; }
        public int FK_IdAutor { get; set; }
        public int FK_IdEditorial { get; set; }
        public int FK_IdGenero { get; set; }
        public string anioDePublicacion { get; set; }
        public string numeroDePaginas { get; set; }
        public string rutaPortada { get; set; }
        public string estado { get; set; }
        public int cantidadEjemplares { get; set; }
        public Nullable<int> cantidadEjemplaresPrestados { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Editorial Editorial { get; set; }
        public virtual Genero Genero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamo> Prestamo { get; set; }
    }
}
