//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElSaberDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestamo()
        {
            this.Devolucion = new HashSet<Devolucion>();
            this.Multa = new HashSet<Multa>();
        }
    
        public int IdPrestamo { get; set; }
        public System.DateTime fechaPrestamo { get; set; }
        public string estado { get; set; }
        public System.DateTime fechaDevolucionEsperada { get; set; }
        public int FK_IdLibro { get; set; }
        public int FK_IdUsuario { get; set; }
        public int FK_IdSocio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devolucion> Devolucion { get; set; }
        public virtual Libro Libro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Multa> Multa { get; set; }
        public virtual Socio Socio { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
